# Generated by Django 2.2 on 2024-03-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_visitcounter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitCounter',
        ),
    ]
